"""adding domain table

Revision ID: 084204e6475d
Revises: a09c8ca13d37
Create Date: 2023-08-12 21:42:54.392238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084204e6475d'
down_revision = 'a09c8ca13d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_channel_web_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('chatbot_channel_main_id', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_channel_main_id'], ['chatbot_channel_main.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_channel_web_domain')
    # ### end Alembic commands ###
