"""table update

Revision ID: 4755261bd23e
Revises: 99d5955ece94
Create Date: 2023-06-22 10:40:10.164180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4755261bd23e'
down_revision = '99d5955ece94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
