"""table updates

Revision ID: aaadfb6f12bc
Revises: 4755261bd23e
Create Date: 2023-06-22 15:52:24.746633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaadfb6f12bc'
down_revision = '4755261bd23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_channel_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_channel_id', sa.String(), nullable=True),
    sa.Column('history_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('human_message', sa.Text(), nullable=True),
    sa.Column('human_message_time', sa.DateTime(), nullable=True),
    sa.Column('ai_message', sa.Text(), nullable=True),
    sa.Column('ai_message_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_channel_id'], ['chatbot_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_channel_history')
    # ### end Alembic commands ###
