"""update id in main table 

Revision ID: bd0de925b24b
Revises: f1c64d8556c0
Create Date: 2023-08-12 19:10:59.173719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0de925b24b'
down_revision = 'f1c64d8556c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_channel_main', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_id', sa.String(), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_channel_main', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('main_id')

    # ### end Alembic commands ###
