import {
  Menu as CMenu,
  Image as CImage,
  Button as CButton,
  Row as CRow,
  Col as CCol,
  Avatar as CAvatar,
  Input as CInput,
  Form as CForm,
  Typography as CTypography,
  Tabs as CTabs,
  Empty as CEmpty,
  message as CMessage,
  Result as CResult,
  Statistic as CStatistic,
  Spin as CSpin,
  Divider as CDivider,
  Tooltip as CToolTip,
  Select as CSelect,
  Slider as CSlider,
  List as CList,
  Space as CSpace,
  ColorPicker as CColorPicker,
  Modal as CModal,
  Dropdown as CDropdown,
  MenuProps as CMenuProps,
  Segmented as CSegmented,
  Badge as CBadge,
  notification as CNotification,
  Popconfirm as CPopconfirm,
  Rate as CRate,
  Carousel as CCarousel,
  Collapse as CCollapse,
} from "antd";

const { TextArea: CTextArea } = CInput;
export * from "./Layout";
export * from "./Card";
export * from "./Upload";

export {
  CMenu,
  CImage,
  CButton,
  CCol,
  CRow,
  CAvatar,
  CInput,
  CTextArea,
  CForm,
  CTypography,
  CTabs,
  CEmpty,
  CMessage,
  CResult,
  CStatistic,
  CSpin,
  CDivider,
  CToolTip,
  CSelect,
  CSlider,
  CList,
  CSpace,
  CColorPicker,
  CModal,
  CDropdown,
  CSegmented,
  CBadge,
  CNotification,
  CPopconfirm,
  CRate,
  CCarousel,
  CCollapse,
};

export type { CMenuProps };
